### ISSUE TITLE
please add production (gerber) data

### ISSUE THREAD

**Issue by NeoFromMatrix** [solokeys/solo-hw#4]
Please add a non panelized version of the gerber files.
Also PCB specifications would be helpful (e.g. 1.6mm for USB-A...)

**Comment by NeoFromMatrix** [comment]
Are present in releases and not in the repo directly as maintainer wants.

**Comment by emosenkis** [comment]
@conorpp can you confirm the following details are correct for all versions of the hardware (I couldn't find this info in the releases)?
PCB thickness: 1.6mm
Copper weight: 1oz.

**Comment by conorpp** [comment]
USB-A should be between 2.2-2.4mm.  2.0 is more common and can work, but
will be a bit thin in the USB socket.

USB-C should be 0.8mm.
