### ISSUE TITLE
Please add BOM

### ISSUE THREAD

**Issue by NeoFromMatrix** [solokeys/solo-hw#5]
Please add a BOM in cvs format for each hw version.

**Comment by conorpp** [comment]
In the releases.  I plan to release each hardware revision as a Github release with the respective BOM/Schematic/Gerbers attached.

**Comment by NeoFromMatrix** [comment]
Oh, ok, thb. I didn't look there. I can understand the reason to add it under the releases. 
Maybe you can also add it to the repo directly, then you'd also get it with a git clone directly.

**Comment by conorpp** [comment]
I don't like putting it in git directly, because quickly it will get out of date with layout/schematic changes.

**Comment by NeoFromMatrix** [comment]
Ok, I'll close both issues. Thanks for the fast feedback!
